### ISSUE TITLE
ACL are not preserved

### ISSUE THREAD

**Issue by inkstak** [CleverCloud/cellar-migration#4]
When migrating with the tool, the ACL are not preserved from one bucket to another.

A file might be readable by everyone in Cellar V1.
A file migrated will have read right to owner in Cellar V2.

**Comment by BlackYoup** [comment]
@inkstak Hello and thanks for the issue!

I'm not sure to fully understand the ` A file migrated will have read right to owner in Cellar V2.` part. If the public-read ACL is applied on the file on Cellar V1, it should also be applied on the file on Cellar v2 (unless a bug has been introduced since then). If the ACL is on the Cellar V1 bucket then yes, It's not yet supported but I was waiting to see if there were users using this feature.

Also, feel free to contact us on our support chat and ask for Arnaud about the Cellar migration, I'll get back to you!
